# -*- coding: utf-8 -*-
"""Model_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iaEanqn4KFyVA-DFIw4lzVFZkAxX_OWI
"""

!pip install ultralytics

import os
print(os.listdir("/content"))

import zipfile

with zipfile.ZipFile("/content/datasets.zip", 'r') as zip_ref:
    zip_ref.extractall("/content/")

print(os.listdir("/content/datasets"))

from ultralytics import YOLO

model = YOLO("yolov8s.pt")

model.train(
    data="/content/datasets/data.yaml",
    epochs=30,
    imgsz=640
)

from google.colab import files

files.download("/content/runs/detect/train-2/weights/best.pt")

from ultralytics import YOLO

model = YOLO("/content/runs/detect/train-2/weights/best.pt")

results = model.predict(
    source="/content/input_sample_video.mp4",
    stream=True,
    conf=0.25,
    save=True
)

for r in results:
    boxes = r.boxes

!pip install ultralytics